### ISSUE TITLE
Bug with Food Spawn

### ISSUE THREAD

**Issue by romandykyi** [ILLIAK31/Snake#2]
### Video
![record_000001](https://github.com/ILLIAK31/Snake/assets/94003504/3a0080eb-b4dd-432f-9242-0b025612f201)

### How to reproduce?
Play normally until the bug appears.
To notice the bug quicker you can in the line 34 in 'Snake.cpp' replace
  ```c++
  std::uniform_int_distribution<int> dist(0, 19); 
  ```
  with:
  ```c++
  std::uniform_int_distribution<int> dist(10, 13);
  ``` 

### What happens?
At first glance, it appears that the snake is not eating an apple. However, the snake is indeed eating the apple correctly. The problem arises because a new apple spawns at the same position as the previous one. This occurs because the apple spawns before the new head position of the snake is updated.

### How to fix it?
To resolve this, update the snake's new position before spawning the food. For instance:
```c++
void Snake::Update()
{
    int newX = snake[0].x + X;
    int newY = snake[0].y + Y;
    if (newX < 0 || newX >= 20 || newY < 0 || newY >= 20 || Check_Collision())
    {
        std::cout << "Game Over!\nScore: " << Score << std::endl;
        window.close();
    }
    // Update the snake's new position
    sf::Vector2i newHead(newX, newY);
    snake.insert(snake.begin(), newHead);
    // And only after this spawn new apple(if needed)
    if (newX == food.x && newY == food.y)
    {
        Score += 10;
        Spawn_Food();
    }
    else
        snake.pop_back();
}
```
**Note:** This issue has already been resolved in pull request #1 .

**Comment by ILLIAK31** [comment]
The issue has been resolved :)

**Comment by romandykyi** [comment]
Yes.
